### ISSUE TITLE
Question: Why is `_special_comments['TITLE']` a list?

### ISSUE THREAD

**Issue by buhtz** [karlicoss/orgparse#51]
Sorry for asking as an Issue but I couldn't find another "channel" for that.

I am new to `orgparse` and org syntax. I would like to know why the `TITLE` entry in `_special_comments` is of type list? In my cases there is only one entry not more. In what cases would there be more then one element in that list? Maybe you can give an example org file to illustrate that.

```python3
>>> orgobj._special_comments['TITLE']
['My Title']
```

**Comment by karlicoss** [comment]
Hi! No worries, it's an okay channel :) 

It seems that it's just the generic way parsing was implemented (because some special properties can be a list): https://github.com/karlicoss/orgparse/blob/349a61f7ba3f0cbdc753a780179b456b1ecb6038/orgparse/node.py#L795

In principle, you shouldn't need to use `_special_comments`, it's kinda internal field. There are `get_file_property_list` and `get_file_property` methods, and the latter can be used with `TITLE` to give you a single value. Hope it helps :) 

https://github.com/karlicoss/orgparse/blob/349a61f7ba3f0cbdc753a780179b456b1ecb6038/orgparse/node.py#L1048-L1058
